# Generated by Django 2.0.1 on 2019-03-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuxPosCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'aux_pos_count',
            },
        ),
        migrations.CreateModel(
            name='AuxWordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'aux_word_count',
            },
        ),
        migrations.CreateModel(
            name='AuxWordPosCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'aux_word_pos_count',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=15, null=True)),
                ('path', models.CharField(blank=True, max_length=192, null=True)),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='PosInvertedIndex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=10, null=True)),
                ('start_offset', models.IntegerField(blank=True, null=True)),
                ('end_offset', models.IntegerField(blank=True, null=True)),
                ('pos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PosInvertedIndex',
            },
        ),
        migrations.CreateModel(
            name='SenseInvertedIndex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=20, null=True)),
                ('start_offset', models.IntegerField(blank=True, null=True)),
                ('end_offset', models.IntegerField(blank=True, null=True)),
                ('pos', models.IntegerField(blank=True, null=True)),
                ('rdd_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SenseInvertedIndex',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('part_of_speech', models.TextField(blank=True, null=True)),
                ('pos', models.IntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(db_column='fk_document_id', on_delete=django.db.models.deletion.DO_NOTHING, to='common_utils.Document')),
            ],
            options={
                'db_table': 'Sentence',
            },
        ),
        migrations.CreateModel(
            name='WordInvertedIndex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=20, null=True)),
                ('start_offset', models.IntegerField(blank=True, null=True)),
                ('end_offset', models.IntegerField(blank=True, null=True)),
                ('pos', models.IntegerField(blank=True, null=True)),
                ('rdd_date', models.DateField(blank=True, null=True)),
                ('sentence', models.ForeignKey(db_column='fk_sentence_id', on_delete=django.db.models.deletion.DO_NOTHING, to='common_utils.Sentence')),
            ],
            options={
                'db_table': 'WordInvertedIndex',
            },
        ),
        migrations.AddField(
            model_name='senseinvertedindex',
            name='sentence',
            field=models.ForeignKey(db_column='fk_sentence_id', on_delete=django.db.models.deletion.DO_NOTHING, to='common_utils.Sentence'),
        ),
        migrations.AddField(
            model_name='posinvertedindex',
            name='sentence',
            field=models.ForeignKey(db_column='fk_sentence_id', on_delete=django.db.models.deletion.DO_NOTHING, to='common_utils.Sentence'),
        ),
        migrations.AlterUniqueTogether(
            name='auxwordposcount',
            unique_together={('word', 'tag', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='auxwordcount',
            unique_together={('token', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='auxposcount',
            unique_together={('token', 'date')},
        ),
    ]
