# Generated by Django 2.0.1 on 2019-03-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_utils', '0002_entryeditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryeditor',
            name='content',
        ),
        migrations.AddField(
            model_name='entryeditor',
            name='cells',
            field=models.TextField(default='[]', verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='entryeditor',
            name='word',
            field=models.CharField(default='', max_length=32, verbose_name='词条名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entryeditor',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
    ]
