# Generated by Django 2.0.1 on 2019-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_utils', '0003_auto_20190326_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryeditor',
            name='word',
            field=models.CharField(default='', max_length=32, verbose_name='词条名'),
        ),
    ]
