# Generated by Django 2.0.1 on 2019-03-27 22:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common_utils', '0004_auto_20190326_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryeditor',
            name='cells',
            field=jsonfield.fields.JSONField(default='[]', verbose_name='内容'),
        ),
    ]
