# Generated by Django 2.0.1 on 2019-04-02 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common_utils', '0005_auto_20190327_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='标题')),
                ('word', models.CharField(default='', max_length=32, verbose_name='笔记本名')),
                ('cells', jsonfield.fields.JSONField(default='[]', verbose_name='内容')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('kernel_id', models.UUIDField(null=True, verbose_name='内核id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
