# Generated by Django 2.0.1 on 2019-04-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_utils', '0006_notebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='word',
        ),
    ]
