# Generated by Django 2.0.1 on 2019-04-17 15:51

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common_utils', '0007_remove_notebook_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryEditorCheckpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bak', models.CharField(max_length=32, verbose_name='标题')),
                ('word_bak', models.CharField(default='', max_length=32, verbose_name='词条名')),
                ('cells_bak', jsonfield.fields.JSONField(default='[]', verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entryeditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_utils.EntryEditor')),
            ],
        ),
    ]
