# Generated by Django 2.0.1 on 2019-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_utils', '0010_auto_20190417_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryeditor',
            name='status',
            field=models.CharField(choices=[('UNINITIALIZED', '未初始化'), ('NORMAL', '正常'), ('MERGING', '合并中')], default='NORMAL', max_length=32),
        ),
        migrations.AddField(
            model_name='entryeditorcheckpoint',
            name='status_bak',
            field=models.CharField(choices=[('UNINITIALIZED', '未初始化'), ('NORMAL', '正常'), ('MERGING', '合并中')], default='NORMAL', max_length=32),
        ),
    ]
