# Generated by Django 2.0.1 on 2019-05-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_utils', '0011_auto_20190506_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryEditorFork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common_utils.EntryEditor')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='common_utils.EntryEditor')),
            ],
        ),
    ]
